# Generated by Django 2.2.1 on 2019-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0002_textcopy_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcopy',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
