# Generated by Django 2.2.1 on 2019-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0003_textcopy_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
            ],
        ),
    ]
